# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60d3fe4168e94f24f89ec3afc9982308420c052ddfc024a5ec35b76438850dc9ff68637fdea5b6a11c9264e3b66ebba3208db009f686c7934ef4fb66da6ec562

test:
  secret_key_base: 3846aeb4de98b0b74b4c42d739e31de26239a9cec99a6360bde7e93cf487e3b7947a6b56d47a2eeaa1e4108e6c8c828aab2461237e2446417fda03e6d4848550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
